/**
 * Generated by `npm run assets:import` — do not edit by hand.
 *
 * Maps engine asset keys to imported artwork in public/assets/. Anything not
 * listed here keeps the procedural placeholder from src/art/placeholder.ts.
 */
export const GENERATED_MANIFEST: Record<string, string> = {};
