/**
 * The pure middle of the importer: extracted archives in, PNG bytes out.
 *
 * Kept free of filesystem and network access so the whole slice-and-remap path
 * can be integration tested against a synthetic pack. The CLI is then a thin
 * shell that fetches, calls this, and writes what comes back.
 */

import { composeAtlas, decodePng, encodePng } from './atlas.mjs';
import { findEntry } from './pack.mjs';
import { planOutput } from './config.mjs';

/**
 * @param {object} params
 * @param {{outputs: any[], packs: any[]}} params.config
 * @param {Record<string, number>} params.tileEnum
 * @param {Map<string, Record<string, Uint8Array>>} params.archives  packId -> extracted files
 * @param {any[]} [params.outputs]  subset of config.outputs to build
 * @returns {{ artifacts: {key:string,file:string,bytes:Uint8Array,width:number,height:number}[],
 *             manifest: Record<string,string>, warnings: string[] }}
 */
export function buildOutputs({ config, tileEnum, archives, outputs = config.outputs }) {
  const artifacts = [];
  /** @type {Record<string,string>} */
  const manifest = {};
  const warnings = [];

  for (const output of outputs) {
    const files = archives.get(output.pack);
    if (!files) throw new Error(`No archive loaded for pack "${output.pack}" (output "${output.key}")`);

    const source = decodePng(findEntry(files, output.source));
    const plan = planOutput(output, tileEnum);
    warnings.push(...plan.warnings);

    const composed = composeAtlas({
      source,
      cellW: output.cellW,
      cellH: output.cellH,
      sourceColumns: output.sourceColumns,
      outputColumns: plan.outputColumns,
      order: plan.order,
    });

    artifacts.push({
      key: output.key,
      file: output.file,
      bytes: encodePng(composed),
      width: composed.width,
      height: composed.height,
    });
    manifest[output.key] = `assets/${output.file}`;
  }

  return { artifacts, manifest, warnings };
}

/**
 * The manifest is generated rather than hand-edited so that deleting an output
 * from the config actually removes it from the game, instead of leaving a
 * dangling entry pointing at a file that no longer exists.
 */
export function renderManifest(manifest) {
  const entries = Object.entries(manifest)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, path]) => `  '${key}': '${path}',`)
    .join('\n');

  return `/**
 * Generated by \`npm run assets:import\` — do not edit by hand.
 *
 * Maps engine asset keys to imported artwork in public/assets/. Anything not
 * listed here keeps the procedural placeholder from src/art/placeholder.ts.
 */
export const GENERATED_MANIFEST: Record<string, string> = {${entries ? `\n${entries}\n` : ''}};
`;
}

export function renderCredits(packs) {
  const sections = packs
    .map((pack) =>
      [
        `## ${pack.name}`,
        '',
        `- Author: ${pack.author}`,
        `- License: ${pack.license}`,
        pack.homepage ? `- Source: ${pack.homepage}` : null,
        pack.sha256 ? `- Archive SHA-256: \`${pack.sha256}\`` : null,
      ]
        .filter(Boolean)
        .join('\n'),
    )
    .join('\n\n');

  return `# Credits

Third-party artwork used in this game. Generated by \`npm run assets:import\`.

${sections || '_No third-party art imported yet; all current art is generated procedurally._'}

## Everything else

All code, and the placeholder art generated at runtime by
\`src/art/placeholder.ts\`, is part of this project.
`;
}
